version: "3.3"
services:
  web:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - '8069:8069'
    volumes:
      - odoo-web-data:/var/lib/odoo17
      - ./config:/etc/odoo17
      - ./addons:/etc/extra-addons
  db:
    image: postgres:16
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgrsql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
volumes:
  odoo-web-data:
  odoo-db-data: